# Generated by Django 5.2.16 on 2026-07-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0002_alter_userbook_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
