# Generated by Django 5.2.16 on 2026-07-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0003_alter_userbook_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
